# Generated by Django 5.0.3 on 2024-03-10 17:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_notes', models.TextField(blank=True)),
                ('game_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_name', models.CharField(max_length=32, unique=True)),
                ('season_notes', models.TextField(blank=True)),
                ('season_type', models.IntegerField(choices=[(3, 'Sanma (3-player)'), (4, 'Riichi Mahjong (4-player)')], default=4)),
                ('season_active', models.BooleanField(default=True)),
                ('season_starting_points', models.IntegerField(choices=[(25000, '25,000'), (30000, '30,000'), (35000, '35,000')], default=30000)),
                ('season_oka', models.IntegerField(default=0)),
                ('uma_big', models.IntegerField(default=20)),
                ('uma_small', models.IntegerField(default=10)),
                ('season_slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_penalty', models.IntegerField(default=0)),
                ('score_final', models.IntegerField()),
                ('score_position', models.IntegerField(choices=[(1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th'), (5, '5th')])),
                ('score_uma', models.IntegerField()),
                ('score_impact', models.FloatField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.game')),
                ('player_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='league.player')),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('player_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='league.player')),
                ('season_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.season')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='season_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='league.season'),
        ),
    ]
