# Generated by Django 5.0.3 on 2024-03-05 18:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_base', models.IntegerField()),
                ('game_notes', models.TextField(blank=True)),
                ('game_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_name', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_name', models.CharField(max_length=32, unique=True)),
                ('season_notes', models.TextField(blank=True)),
                ('season_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_starting', models.IntegerField()),
                ('score_penalty', models.IntegerField()),
                ('score_final', models.IntegerField()),
                ('score_position', models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Fifth')])),
                ('rank_uma', models.IntegerField()),
                ('rank_impact', models.FloatField()),
                ('rank_final', models.FloatField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.game')),
                ('player_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='league.player')),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('player_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='league.player')),
                ('season_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.season')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='season_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='league.season'),
        ),
    ]
