# Generated by Django 5.0.3 on 2024-03-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='discarded_riichi_sticks',
            field=models.IntegerField(default=0),
        ),
    ]
