# Generated by Django 5.0.3 on 2024-03-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_season_season_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='season_slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
