# Generated by Django 5.0.3 on 2024-03-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_alter_game_discarded_riichi_sticks'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_number_in_season',
            field=models.IntegerField(default=1),
        ),
    ]
