# Generated by Django 5.0.3 on 2024-04-20 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_game_game_number_in_season'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='player_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='season',
            old_name='season_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='season',
            old_name='season_oka',
            new_name='oka',
        ),
        migrations.RenameField(
            model_name='season',
            old_name='season_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='season',
            old_name='season_starting_points',
            new_name='starting_points',
        ),
    ]
