# Generated by Django 5.0.3 on 2024-03-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_alter_season_season_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='season_type',
            field=models.IntegerField(choices=[(3, 'Sanma (3-player)'), (4, 'Riichi Mahjong (4- or 5-player)')], default=4),
        ),
        migrations.AlterField(
            model_name='score',
            name='score_position',
            field=models.IntegerField(choices=[(1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th'), (5, '5th')]),
        ),
    ]
