# Generated by Django 5.0.3 on 2024-03-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_season_season_type_alter_score_score_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='season_type',
            field=models.IntegerField(choices=[(3, 'Sanma (3-player)'), (4, 'Riichi Mahjong (4- and 5-player)')], default=4),
        ),
    ]
