# Generated by Django 5.0.3 on 2024-03-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0006_alter_season_season_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='score_base',
        ),
        migrations.RemoveField(
            model_name='score',
            name='score_starting',
        ),
        migrations.AddField(
            model_name='season',
            name='season_starting_points',
            field=models.IntegerField(choices=[(25000, '25,000'), (30000, '30,000'), (35000, '35,000')], default=30000),
        ),
        migrations.AddField(
            model_name='season',
            name='season_target_points',
            field=models.IntegerField(choices=[(30000, '30,000'), (35000, '35,000'), (40000, '40,000')], default=35000),
        ),
        migrations.AddField(
            model_name='season',
            name='season_use_oka',
            field=models.BooleanField(default=False),
        ),
    ]
