# Generated by Django 5.0.3 on 2024-03-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0007_remove_game_score_base_remove_score_score_starting_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='season_target_points',
        ),
        migrations.RemoveField(
            model_name='season',
            name='season_use_oka',
        ),
        migrations.AddField(
            model_name='season',
            name='season_oka',
            field=models.IntegerField(default=0),
        ),
    ]
