# Generated by Django 5.0.3 on 2024-03-06 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0008_remove_season_season_target_points_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uma',
            fields=[
                ('uma_name', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('uma_1st', models.IntegerField()),
                ('uma_2nd', models.IntegerField()),
                ('uma_3rd', models.IntegerField()),
                ('uma_4th', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='season',
            name='season_uma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='league.uma'),
        ),
    ]
