# Generated by Django 5.0.3 on 2024-03-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0009_uma_season_season_uma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='season_uma',
        ),
        migrations.AddField(
            model_name='season',
            name='uma_1st',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='season',
            name='uma_2nd',
            field=models.IntegerField(default=10),
        ),
        migrations.DeleteModel(
            name='Uma',
        ),
    ]
