# Generated by Django 5.0.3 on 2024-03-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0010_remove_season_season_uma_season_uma_1st_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='rank_final',
            new_name='score_impact',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='rank_uma',
            new_name='score_uma',
        ),
        migrations.RemoveField(
            model_name='score',
            name='rank_impact',
        ),
        migrations.AlterField(
            model_name='season',
            name='season_type',
            field=models.IntegerField(choices=[(3, 'Sanma (3-player)'), (4, 'Riichi Mahjong (4-player)')], default=4),
        ),
    ]
