# Generated by Django 5.0.3 on 2024-03-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0011_rename_rank_final_score_score_impact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
