# Generated by Django 5.0.3 on 2024-03-06 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0013_season_uma_3rd_season_uma_4th'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='uma_3rd',
        ),
        migrations.RemoveField(
            model_name='season',
            name='uma_4th',
        ),
    ]
