# Generated by Django 5.0.3 on 2024-03-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0014_remove_season_uma_3rd_remove_season_uma_4th'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score_penalty',
            field=models.IntegerField(default=0),
        ),
    ]
