# Generated by Django 5.0.3 on 2024-03-06 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0015_alter_score_score_penalty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='uma_1st',
            new_name='uma_big',
        ),
        migrations.RenameField(
            model_name='season',
            old_name='uma_2nd',
            new_name='uma_small',
        ),
    ]
